from .ascii_art import print_rotated_gradient # 1
from .clear import clear # 2
from .print import typewrite # 3
from .int_input import inputInt # 4
from .str_input import inputStr # 5
from .rainbow_print import rainbow_print # 6
from .marquee import marquee # 7
from .box_print import box_print # 8
from .confirm import confirm # 9
from .progress import progress # 10
from .spinner import spinner # 11
from .dots_loading import dots_loading # 12
from .countdown import countdown # 13
from .percent_loader import percent_loader # 14
from .roll_dice import roll_dice # 15
from .coin_flip import flip_coin # 16
from .matrix_rain import matrix_rain # 17